# Generated by Django 4.2.5 on 2023-11-26 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improver', '0004_link_link_uniqueness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA=z]*$', 'Only letters allowed')]),
        ),
    ]
