# Generated by Django 4.2.5 on 2024-02-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improver', '0006_alter_word_word_word_word_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='random_nr',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.001, max_digits=4, null=True),
        ),
    ]
