# Generated by Django 4.2.5 on 2024-02-20 19:54

from django.db import migrations, models
import django.db.models.functions.math


class Migration(migrations.Migration):

    dependencies = [
        ('improver', '0006_alter_word_word_word_word_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='random_nr',
            field=models.DecimalField(blank=True, decimal_places=3, default=django.db.models.functions.math.Random(), max_digits=4, null=True),
        ),
    ]
