# Generated by Django 4.2.5 on 2023-09-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='impuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
