# Generated by Django 4.2.5 on 2023-11-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_impuser_is_active_impuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
